// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9KVUVYrjACLyC8vrLiDq5j5W5L7vKPY',
    appId: '1:143056683978:web:cc16c6365fb583b735c533',
    messagingSenderId: '143056683978',
    projectId: 'mg-hospital-a819a',
    authDomain: 'mg-hospital-a819a.firebaseapp.com',
    storageBucket: 'mg-hospital-a819a.firebasestorage.app',
    measurementId: 'G-P2EDBKP4SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7RpD1IrnuOjMM3nCrIa_AuWE5cExyCeQ',
    appId: '1:143056683978:android:d2b349998bbd355835c533',
    messagingSenderId: '143056683978',
    projectId: 'mg-hospital-a819a',
    storageBucket: 'mg-hospital-a819a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9KVUVYrjACLyC8vrLiDq5j5W5L7vKPY',
    appId: '1:143056683978:web:d25cbdcbcb131ce335c533',
    messagingSenderId: '143056683978',
    projectId: 'mg-hospital-a819a',
    authDomain: 'mg-hospital-a819a.firebaseapp.com',
    storageBucket: 'mg-hospital-a819a.firebasestorage.app',
    measurementId: 'G-5T6Q9XRN3H',
  );
}
